### PR TITLE
Removed 'assets' field in react-native.config.js

### LINKED ISSUE #86: Warning with new RN version 0.69+
**Description**
Package react-native-math-view contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**To Reproduce**
Add a reference inside package.json to a project pointing to latest RN version and run for iOS. The warn message will appear in the output terminal

**Expected behavior**
No warning is shown

### PR DESCRIPTION
**Pull request by rrr3da**
closes #86

### CODE REVIEW

**Comment by ShaMan123** [comment]
Can you confirm it builds as expected on both ios and android?

**Comment by rrr3da** [comment]
Well, I just removed an empty array from the configuration...
Same thing was done on other third party RN packages to remove the warning message.

What should I do to build the plugin?
Is there any specific command I should run?

**Comment by ShaMan123** [comment]
If the example app starts all is good
https://github.com/ShaMan123/react-native-math-view#running-example-app
But it has been a long time since I touched it so it needs a bump in RN
Are you up for that?

Do you have any docs pointing to this change?

Sorry for being a nag, I lost track and interest of RN ecosystem so it is a shot in the dark all this.
I do remember RN was (still is?) a nightmare in terms of config and upgrade and extremely fragile so I want to exercise a bit of caution.

Since it is as you say it seems safe.
Though I don't remember why I wanted to use it and commented those lines.

**Review by ShaMan123 — APPROVED** [review]

**Comment by ShaMan123** [comment]
I see here it was removed https://github.com/react-native-community/cli/blob/8.x/docs/dependencies.md

Unfortunately there is not maintained CHANGELOG

Found it 
https://github.com/react-native-community/cli/releases/tag/v8.0.0-alpha.0

**Pull request merged**
